server:
  port: 9191
  servlet:
    encoding:
      force-response: true

spring:
  profiles:
    default: local
    include: oauth
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      username: sa
      password:
    url: jdbc:h2:~/test;AUTO_SERVER=TRUE;
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
  output:
    ansi:
      enabled: always
logging:
  level:
    org.hibernate:
      type: debug
      sql: debug
    org.springframework: debug
